### ISSUE TITLE
Should js-yaml be loaded via NPM?

### ISSUE THREAD

**Issue by Ajedi32** [jonschlinkert/gray-matter#18]
I noticed that a minified version of js-yaml seems to be included in this project's `lib/` directory. Shouldn't that dependency be pulled in via npm instead?

**Comment by jonschlinkert** [comment]
it's minified to keep load times as fast as possible since js-yaml includes a lot of unnecessary files in the npm releases.  it's updated by a build step https://github.com/jonschlinkert/gray-matter/blob/master/gulpfile.js#L22. however, we recently did a pr to reduce the number of files in the releases, so it might be okay to start requiring it in again. if you'd like to do a pr I'd be happy to accept as long as all tests still pass. thanks

**Comment by Ajedi32** [comment]
Okay, I'll give it a shot.
