### ISSUE TITLE
Depth

### ISSUE THREAD

**Issue by rickysullivan** [jonschlinkert/gray-matter#27]
Is there a depth limit at all?

```
images:
  a:
    image:
      title: 'title'
```

Returns:

```
 images: { a: { image: [Object] } },
```

**Comment by rickysullivan** [comment]
I found someone else with similar issue, only it's to do with the dependancy **js-yaml**

https://github.com/nodeca/js-yaml/issues/176

**Comment by jonschlinkert** [comment]
It's not really a js-yaml issue, it's how the node.js `console.log()` method shows objects in the console. The advice they gave in that issue explains how you would show objects to a greater depth. 

I also found that confusing when I started programming in node. Closing since this isn't really an issue, but I'm happy to help if you have questions.

**Comment by rickysullivan** [comment]
Thank you for this. I was pulling my hair out!

**Comment by jonschlinkert** [comment]
No problem! I completely get it.
