### ISSUE TITLE
Merge changes upstream?

### ISSUE THREAD

**Issue by josephearl** [jonschlinkert/gray-matter#38]
I have a [fork of gray-matter](https://github.com/josephearl/preliminaries) that splits out the core from the parsers, similar to the [currently open PR](https://github.com/jonschlinkert/gray-matter/pull/15). Parsers can define custom delimiters to enable auto-detection of that format.

Stringifying is supported for all languages. I've also removed the strict option in favor of just throwing errors.

I'd be happy to contribute the changes back in some form if you're interested. There are some changes to the interface in my fork - I opted for a .parse and .stringify to match JSON - but that should be simple enough to undo to make it feasible.

**Comment by jonschlinkert** [comment]
@josephearl sorry for the very late reply. I'm interested in collaborating on this. I'll add you as a collab.

One thing I've mentioned in another issue somewhere that I think would be nice to do is to use an existing convention for the parsers (lol [I like parsers](https://github.com/jonschlinkert?utf8=%E2%9C%93&tab=repositories&q=parse&type=&language=)). 

I'm open to anything, but a couple examples are [parsers](https://github.com/jonschlinkert/parsers) and [parser-cache](https://github.com/jonschlinkert/parser-cache) (it's been long enough that I don't remember why I created both and what the main differentiation was going to be between the two). 

In any case, the main goal would be to allow parsers to be registered the same way engines are with [consolidate](https://github.com/tj/consolidate.js/). I don't mind if you'd prefer to build the parsers into gray-matter, but it would still probably be nice to follow a convention (even the one you're using) so that implementors can use other parsers if they wish. This would also allow us to use these parsers for other non-front-matter purposes (we have "data loaders" in [assemble](https://github.com/assemble/assemble) that could use this).

does any of this sound ok? again I'm open to whatever. If you want me to add you to this lib, I'd be happy to.
