### ISSUE TITLE
Support multiple delimiters.

### ISSUE THREAD

**Issue by tech4him1** [jonschlinkert/gray-matter#46]
Would you consider supporting multiple types of delimiters at one time, or is there already a way do do it? For example, I would like to be able to parse front matter beginning with `---`, `+++`, or `~~~`.

**Comment by donaldtone** [comment]
options.delimiters
Type: String

Default: ---

Open and close delimiters can be passed in as an array of strings.

Example:

// format delims as a string
matter.read('file.md', {delims: '~~~'});
// or an array (open/close)
matter.read('file.md', {delims: ['~~~', '~~~']});

the example is wrong.
it should use delimiters instead of delims.
like that:
Example:

// format delims as a string
matter.read('file.md', {delimiters: '~~~'});
// or an array (open/close)
matter.read('file.md', {delimiters: ['~~~', '~~~']});
