### ISSUE TITLE
consider removing fs

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/gray-matter#50]
The goal is to make gray-matter easier to use in browsers/non-node.js environments. 

Related: https://github.com/jonschlinkert/gray-matter/issues/49

My first thought is that we could achieve this by publishing `gray-matter-fs` or something. Any other ideas?

cc @tech4him1

**Comment by jonschlinkert** [comment]
just saw [this comment](https://github.com/jonschlinkert/gray-matter/issues/49#issuecomment-329635570). That might be a solution too.

**Comment by tech4him1** [comment]
> Another way that would work for us if you don't want to change the sources would be to have a re-packaged version for browsers that was run through Babel or something like that and left out the Node functions like `matter.read`/`fs`.

If we did it that way, then you should be able to build the sources however you want, then publish it as two separate packages (maybe `gray-matter` and `gray-matter-browser` or something like that).

**Comment by jonschlinkert** [comment]
> If we did it that way, then you should be able to build the sources however you want, then publish it as two separate packages (maybe gray-matter and gray-matter-browser or something like that).

yeah, that's not a bad idea. Let me think about it for a little bit (today). @doowb?

**Comment by tech4him1** [comment]
Another option if we are just considering `fs` is wrapping the `require` in an `if (require) { require('fs'); }`.

**Comment by jonschlinkert** [comment]
what if we did `gray-matter-lite` or something, then we could require that into this module for the time being to keep the API the same here.

**Comment by tech4him1** [comment]
That sounds really good.

**Comment by doowb** [comment]
I like the idea of having a separate module with browser compatible features that is then required into `gray-matter`.

The `if(require) { require('fs'); }` won't work for webpack because webpack does static analysis to determine which modules to include by looking at the `require` keyword.

Another option that might work is for `gray-matter` to add a `browser` property to `package.json` with `{"fs": false}` since webpack supports [the package browser field spec](https://github.com/defunctzombie/package-browser-field-spec) now. I haven't tested this to know if it would work for you or not.

**Comment by erquhart** [comment]
That would be awesome.

**Comment by tech4him1** [comment]
This is working as of version 3.0.6. Thanks!

**Comment by jonschlinkert** [comment]
> This is working as of version 3.0.6. Thanks!

Great! I was going to ask. Thanks!
