### ISSUE TITLE
{ excerpt: true } option returns empty string

### ISSUE THREAD

**Issue by reccanti** [jonschlinkert/gray-matter#52]
Given a sample file:
```html
---
title: Hello
slug: home
---
<html>
    <h1>Hello world!</h1>
    <!-- end -->
    <p>How are you?</p>
</html>
```

And the following code
```js
var fs = require('fs');
var matter = require('gray-matter');
var str = fs.readFileSync('example.html', 'utf8');
console.log(matter(str, {excerpt: true}));
```

gray-matter produces the following output:

```
{ content: '<html>\n    <h1>Hello world!</h1>\n    <!-- end -->\n    <p>How are you?</p>\n</html>',
  data: { title: 'Hello', slug: 'home' },
  excerpt: '' }
```

It does work if I use an excerpt separator, though

```js
var fs = require('fs');
var matter = require('gray-matter');
var str = fs.readFileSync('example.html', 'utf8');
console.log(matter(str, {excerpt_separator: '<!-- end -->'}));
```

```
{ content: '<html>\n    <h1>Hello world!</h1>\n    <!-- end -->\n    <p>How are you?</p>\n</html>',
  data: { title: 'Hello', slug: 'home' },
  excerpt: '<html>\n    <h1>Hello world!</h1>\n    ' }
```

**Comment by doowb** [comment]
When `{excerpt: true}` is set, the `excerpt_separator` defaults to the front-matter delimiter. In this case, it would be `---`. 

Since your sample file is using `<!-- end -->` as the `excerpt_separaor`, then you need to set that on the options. This seems to be working as intended.

You can either change the `<!-- end -->` in the sample file to `---` or set the `excerpt_separator` like in the second example.

You can also set `excerpt` to a function so you can control how the excerpt is extracted from the file:

```js
{
  excerpt: function(file, options) {
    // returns the first 4 lines of the contents
    return file.content.split('\n').slice(0, 4).join('\n');
  }
}
```

**Comment by reccanti** [comment]
Thanks @doowb, that worked for me! I wasn't aware of `---` being the default excerpt_separator from the documentation, and I didn't realize you could pass a function either. Do you want me to make a PR to update the documentation?

**Comment by doowb** [comment]
A PR would be great! Please update the [.verb.md](https://github.com/jonschlinkert/gray-matter/blob/master/.verb.md#options) file. If you'd like, you can build the README.md file as described in the [Building docs](https://github.com/jonschlinkert/gray-matter#about) section. If not, I'll build the readme after merging the PR.
